CLASSES=[
"Abyssian Roller",
"Black Woodpecker",
"Blue Tit",
"Carrion Crow",
"Chaffinch",
"Coal Tit",
"Common Blackbird",
"Common Cuckoo",
"Common Firecrest",
"Common Raven",
"Common Wood Pigeon",
"Dunnock",
"Eurasian Blackcap",
"Eurasian Collard Dove",
"Eurasian Hoopoe",
"Eurasian Jay",
"Eurasian Nuthatch",
"Eurasian Turtle Dove",
"Eurasian Wren",
"European Goldfinch",
"European Green Woodpecker",
"European Greenfinch",
"European Robin",
"European Roller",
"European Starling",
"Goldcrest",
"Golden Oriole",
"Great Tit",
"Grey-headed Woodpecker",
"Hawfinch",
"House Sparrow",
"Long-tailed Tit",
"Magpie",
"Marsh Tit",
"Song Thrush",
"Spotted Woodpecker",
"Stock Dove",
"Tree Sparrow",
"White Wagtail",
"Willow Tit"
]